### ISSUE TITLE
Forced portrait mode, Landscape e gecmemesi lazim

### ISSUE THREAD

**Issue by TopalSinek** [DjCedrics/Augma#16]

**Comment by aburaksahin** [comment]
Now we force portrait on every page, EXCEPT UICamera. UICamera is currently available for both layouts.

Kıslar, Kamerada Landscape olmasın mı?
@TopalSinek @DjCedrics @cgdsyilmaz @canbayraktar1 

[https://i.imgur.com/5jmeecy.mp4](url)
