### ISSUE TITLE
Profile pagede kendi post larinin ve owned circle larinin gorunmesi

### ISSUE THREAD

**Issue by TopalSinek** [DjCedrics/Augma#18]
Su an api da trigger yerine gecicek seyleri bitirdim sayilir. Circle ve Note yaratinca UserData table inada yaziliyo bilgileri. Circle icin circleID, circleName ve circlesearchname i tutuyorum, Note icin noteID, noteText lat/lon tutuyorum locationinida gosterebilmek icin. Bunlarin profile page de gorulebilmesi lazim.

**Comment by aburaksahin** [comment]
Üzerinde çalışmıştım zamanında ancak daha bitmedi. Kısa süre içinde pushlanacak.

**Comment by aburaksahin** [comment]
Profil sayfası sağa kaydırıldığında içinde bulunduğu circleların sayfası açılacak. Sola kaydırıldığında invitationlar (belki genel notification sayfası olarak da kullanabiliriz). Kendi postları zaten galeri şeklinde profil sayfasında bulunmakta.
