### ISSUE TITLE
Photo Saving

### ISSUE THREAD

**Issue by cgdsyilmaz** [DjCedrics/Augma#21]
We need to save photo to three different places:
<strike>1. To session, without logging out we need to be able to get the photo from session.</strike>
2. To S3, if we are going to do a profile search or if a user opens his/her account in a new phone we need to get the photo from S3.
3. To phone memory, if I logged out on my next log in Augma should not get the photo again from S3, but from the phone memory. Also, we can save the photos of users that a user searched to phone for not requesting from S3 again and again (e.g WhatsApp holds a folder for these).

**Comment by aburaksahin** [comment]
We need to contemplate on the 1st practice, I personally disagree, because it can introduce some vulnerabilities. Alternatively, once user establishes his/her session, 3rd practice seems the most viable approach.

**Comment by cgdsyilmaz** [comment]
Edited the issue accordingly.

**Comment by TopalSinek** [comment]
I debugged it a little more and opened the read from internal storage part again. It writes to internal storage, it uploads the file to s3 and reads it from internal storage to refresh it self. Both the profile page and UImain refreshes but there is a issue with caching i think. When it tries to read it from internal storage it reads the old version. But when app restarts it reads the new version correctly atm.

**Comment by aburaksahin** [comment]
Background and profile pictures are now automatically cached to disk & memory.
